apiVersion: v1
kind: Service
metadata:
  name: {{ include "goflow.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "goflow.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.sflow.port }}
      targetPort: {{ .Values.service.sflow.port }} 
      protocol: {{ .Values.service.sflow.protocol }}
      name: sflow
    - port: {{ .Values.service.nflow.port }}
      targetPort: {{ .Values.service.nflow.port }} 
      protocol: {{ .Values.service.nflow.protocol }} 
      name: nflow
  selector:
    {{- include "goflow.selectorLabels" . | nindent 4 }}
