apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-dashboards
  labels:
    grafana_dashboard: "1"
data:
{{- $files := .Files }}
{{- range $key, $value := .Files }}
{{- if hasPrefix "grafana/" $key }}

{{ trimPrefix "grafana/" $key | indent 2 }} : |
{{ $.Files.Get $key | indent 4 }}

{{- end }}
{{- end }}
